"""buat semua tabel

Revision ID: 0001
Revises: 
Create Date: 2026-09-23 02:35:36.390091
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0001'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('checklist_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jabatan', sa.String(length=20), nullable=False),
    sa.Column('urutan', sa.Integer(), nullable=False),
    sa.Column('teks', sa.Text(), nullable=False),
    sa.Column('mode', sa.String(length=10), nullable=False),
    sa.Column('aktif', sa.Boolean(), nullable=False),
    sa.Column('dibuat_pada', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("jabatan IN ('Security', 'OB', 'CS', 'Messenger')", name='ck_item_jabatan'),
    sa.CheckConstraint("mode IN ('harian', 'sesi')", name='ck_item_mode'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_item_jabatan_urutan', 'checklist_item', ['jabatan', 'urutan'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nama', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=160), nullable=False),
    sa.Column('password_hash', sa.String(length=200), nullable=False),
    sa.Column('peran', sa.String(length=20), nullable=False),
    sa.Column('jabatan', sa.String(length=20), nullable=True),
    sa.Column('nip', sa.String(length=40), nullable=False),
    sa.Column('unit', sa.String(length=120), nullable=False),
    sa.Column('telepon', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('terakhir_masuk', sa.DateTime(timezone=True), nullable=True),
    sa.Column('dibuat_pada', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("jabatan IS NULL OR jabatan IN ('Security', 'OB', 'CS', 'Messenger')", name='ck_users_jabatan'),
    sa.CheckConstraint("peran <> 'user' OR jabatan IS NOT NULL", name='ck_users_petugas_berjabatan'),
    sa.CheckConstraint("peran IN ('superadmin', 'admin', 'user')", name='ck_users_peran'),
    sa.CheckConstraint("status IN ('Aktif', 'Cuti', 'Nonaktif')", name='ck_users_status'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('checklist_harian',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('petugas_id', sa.Integer(), nullable=False),
    sa.Column('tanggal', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('diisi_oleh', sa.Integer(), nullable=True),
    sa.Column('dikirim_pada', sa.DateTime(timezone=True), nullable=True),
    sa.Column('dibuat_pada', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('Draf', 'Dikirim')", name='ck_checklist_status'),
    sa.ForeignKeyConstraint(['diisi_oleh'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['petugas_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('petugas_id', 'tanggal', name='uq_checklist_petugas_tanggal')
    )
    op.create_index(op.f('ix_checklist_harian_tanggal'), 'checklist_harian', ['tanggal'], unique=False)
    op.create_table('kendala',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('petugas_id', sa.Integer(), nullable=False),
    sa.Column('dibuat_oleh', sa.Integer(), nullable=True),
    sa.Column('waktu', sa.DateTime(timezone=True), nullable=False),
    sa.Column('keterangan', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('ditangani_oleh', sa.Integer(), nullable=True),
    sa.Column('diperbarui_pada', sa.DateTime(timezone=True), nullable=True),
    sa.Column('dibuat_pada', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('Baru', 'Diproses', 'Selesai')", name='ck_kendala_status'),
    sa.ForeignKeyConstraint(['dibuat_oleh'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['ditangani_oleh'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['petugas_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_kendala_petugas_waktu', 'kendala', ['petugas_id', 'waktu'], unique=False)
    op.create_index(op.f('ix_kendala_status'), 'kendala', ['status'], unique=False)
    op.create_index(op.f('ix_kendala_waktu'), 'kendala', ['waktu'], unique=False)
    op.create_table('lembur',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('petugas_id', sa.Integer(), nullable=True),
    sa.Column('jabatan', sa.String(length=20), nullable=False),
    sa.Column('dibuat_oleh', sa.Integer(), nullable=True),
    sa.Column('tanggal', sa.Date(), nullable=False),
    sa.Column('jam_mulai', sa.Time(), nullable=False),
    sa.Column('jam_selesai', sa.Time(), nullable=False),
    sa.Column('keterangan', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('alasan_tolak', sa.Text(), nullable=True),
    sa.Column('dikirim_pada', sa.DateTime(timezone=True), nullable=True),
    sa.Column('dijawab_pada', sa.DateTime(timezone=True), nullable=True),
    sa.Column('dibuat_pada', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("jabatan IN ('Security', 'OB', 'CS', 'Messenger')", name='ck_lembur_jabatan'),
    sa.CheckConstraint("status = 'Draf' OR petugas_id IS NOT NULL", name='ck_lembur_petugas_wajib'),
    sa.CheckConstraint("status IN ('Draf', 'Menunggu', 'Diterima', 'Ditolak')", name='ck_lembur_status'),
    sa.ForeignKeyConstraint(['dibuat_oleh'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['petugas_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_lembur_status_tanggal', 'lembur', ['status', 'tanggal'], unique=False)
    op.create_table('log_audit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('aksi', sa.String(length=60), nullable=False),
    sa.Column('detail', sa.Text(), nullable=False),
    sa.Column('waktu', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_log_audit_waktu'), 'log_audit', ['waktu'], unique=False)
    op.create_table('logbook',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('petugas_id', sa.Integer(), nullable=False),
    sa.Column('dibuat_oleh', sa.Integer(), nullable=True),
    sa.Column('waktu', sa.DateTime(timezone=True), nullable=False),
    sa.Column('keterangan', sa.Text(), nullable=False),
    sa.Column('dibuat_pada', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['dibuat_oleh'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['petugas_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_logbook_petugas_waktu', 'logbook', ['petugas_id', 'waktu'], unique=False)
    op.create_index(op.f('ix_logbook_waktu'), 'logbook', ['waktu'], unique=False)
    op.create_table('checklist_jawaban',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lembar_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('sesi', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('catatan', sa.Text(), nullable=False),
    sa.CheckConstraint("sesi IN ('Harian', 'Pagi', 'Siang', 'Sore')", name='ck_jawaban_sesi'),
    sa.CheckConstraint("status IN ('Ya', 'Tidak')", name='ck_jawaban_status'),
    sa.ForeignKeyConstraint(['item_id'], ['checklist_item.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['lembar_id'], ['checklist_harian.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lembar_id', 'item_id', 'sesi', name='uq_jawaban_item_sesi')
    )
    op.create_index(op.f('ix_checklist_jawaban_lembar_id'), 'checklist_jawaban', ['lembar_id'], unique=False)
    op.create_table('foto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('logbook_id', sa.Integer(), nullable=True),
    sa.Column('kendala_id', sa.Integer(), nullable=True),
    sa.Column('lokasi_file', sa.String(length=300), nullable=False),
    sa.Column('ukuran_byte', sa.Integer(), nullable=False),
    sa.Column('diambil_pada', sa.DateTime(timezone=True), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.CheckConstraint('(logbook_id IS NOT NULL AND kendala_id IS NULL) OR (logbook_id IS NULL AND kendala_id IS NOT NULL)', name='ck_foto_satu_pemilik'),
    sa.ForeignKeyConstraint(['kendala_id'], ['kendala.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['logbook_id'], ['logbook.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_foto_diambil_pada'), 'foto', ['diambil_pada'], unique=False)
    op.create_index(op.f('ix_foto_kendala_id'), 'foto', ['kendala_id'], unique=False)
    op.create_index(op.f('ix_foto_logbook_id'), 'foto', ['logbook_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_foto_logbook_id'), table_name='foto')
    op.drop_index(op.f('ix_foto_kendala_id'), table_name='foto')
    op.drop_index(op.f('ix_foto_diambil_pada'), table_name='foto')
    op.drop_table('foto')
    op.drop_index(op.f('ix_checklist_jawaban_lembar_id'), table_name='checklist_jawaban')
    op.drop_table('checklist_jawaban')
    op.drop_index(op.f('ix_logbook_waktu'), table_name='logbook')
    op.drop_index('ix_logbook_petugas_waktu', table_name='logbook')
    op.drop_table('logbook')
    op.drop_index(op.f('ix_log_audit_waktu'), table_name='log_audit')
    op.drop_table('log_audit')
    op.drop_index('ix_lembur_status_tanggal', table_name='lembur')
    op.drop_table('lembur')
    op.drop_index(op.f('ix_kendala_waktu'), table_name='kendala')
    op.drop_index(op.f('ix_kendala_status'), table_name='kendala')
    op.drop_index('ix_kendala_petugas_waktu', table_name='kendala')
    op.drop_table('kendala')
    op.drop_index(op.f('ix_checklist_harian_tanggal'), table_name='checklist_harian')
    op.drop_table('checklist_harian')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index('ix_item_jabatan_urutan', table_name='checklist_item')
    op.drop_table('checklist_item')
    # ### end Alembic commands ###
